### ISSUE TITLE
handles ProvisionWarehouseTimeout on provisioning timeout

### ISSUE THREAD

**Issue by flaneur2020** [databendcloud/databend-go#35]
you may get a ProvisionWarehouseTimeout on cloud resource exhausted. This error is safe to retry, because the query is not actually sent to the warehouse.

with this error get handled, the sdk could be more robust on access cloud warehouse from databend cloud.

**Comment by hantmac** [comment]
We has handled  `ProvisionWarehouseTimeout ` [here](https://github.com/databendcloud/databend-go/blob/main/restful.go#L182), but maybe we can handle once retry in func `DoRequest`.
